spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_customer?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    # properties:
    #  hibernate:
    #   dialect: org.hibernate.dialect.MySQL55Dialect
server:
  port: 8092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost