spring:
  application:
    name: combo
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_combo?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  main:
    allow-circular-references: true
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
server:
  port: 8192
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #service-url:
      #defaultZone: http://localhost:8760/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost