server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bajrangkar/spring-cloud-config-store
          search-paths:
            - '*service'
          #username: root //not required for public repos
          #passphrase: 12345 //not required for public repos