server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bajrangkar/microservices-course-on-youtube-config-store
          search-paths:
            - 'service-config/*service'
          #username: root //not required for public repos
          #passphrase: 12345 //not required for public repos